import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'nav.about': 'About',
    'nav.projects': 'Projects',
    'nav.contact': 'Contact',
    'hero.name': 'Igor Lapin',
    'hero.subtitle': 'Backend Architect',
    'hero.title': 'Enterprise-Grade Backend Architect',
    'hero.description': 'I design and implement scalable backend systems where',
    'hero.reliability': 'reliability',
    'hero.description2': 'performance and financial correctness are critical.',
    'hero.industries': 'FinTech • Billing • High-Load • AI Platforms',
    'about.title': 'About Me',
    'about.description': 'Backend Engineer with',
    'about.years': '7+ years',
    'about.description2': 'of commercial experience and',
    'about.leadYears': '2 years',
    'about.description3': 'as a Lead Engineer. Worked with large enterprise systems, financial modules and government integrations.',
    'about.projects': 'I join projects that need:',
    'about.cap1': 'build architecture from scratch',
    'about.cap2': 'implement billing or complex transactional logic',
    'about.cap3': 'prepare system for load growth',
    'about.cap4': 'optimize DB and eliminate OOM / bottleneck',
    'about.cap5': 'integrate AI modules',
    'about.work': 'Available as an independent engineer or',
    'about.fractional': 'fractional tech lead',
    'capabilities.mainTitle': 'What I Do',
    'edu.title': 'Education',
    'edu.master': 'Master\'s degree',
    'edu.masterField': 'Mechatronics, Robotics, and Automation Engineering',
    'edu.masterSchool': 'Karaganda State Technical University · 2017-2019',
    'edu.bachelor': 'Bachelor\'s degree',
    'edu.bachelorField': 'Mechatronics, Robotics, and Automation',
    'edu.bachelorSchool': 'Karaganda State Technical University',
    'lang.title': 'Languages',
    'lang.russian': 'Russian',
    'lang.english': 'English',
    'lang.native': 'Native',
    'lang.professional': 'Full Professional',
    'results.title': 'Key Results',
    'results.1': 'Reduced reporting time from 2 days to 15 minutes (10× improvement)',
    'results.2': 'Decreased peak DB OOM load from 100% to 40%',
    'results.3': 'Reduced workflow errors by 50%',
    'results.4': 'Improved incident resolution time by 60%',
    'results.5': 'Built AI system processing 6,000+ audio files monthly',
    'skills.title': 'Engagement Models',
    'skills.audit': 'Architecture Consulting',
    'skills.auditDesc': 'Current architecture analysis, bottleneck identification and improvement recommendations',
    'skills.backend': 'Full Backend Implementation',
    'skills.backendDesc': 'Complete development cycle from design to production deployment',
    'skills.performance': 'Performance Optimization',
    'skills.performanceDesc': 'Eliminating bottlenecks, DB optimization, reducing load and response time',
    'skills.ai': 'AI Integration',
    'skills.aiDesc': 'Designing and implementing AI modules in existing systems',
    'skills.lead': 'Fractional Tech Lead',
    'skills.leadDesc': 'Technical leadership and architectural decisions on a project basis',
    'exp.title': 'Enterprise Experience',
    'exp.yandex': 'Yandex',
    'exp.yandexRole': 'Billing Architecture',
    'exp.yandex1': 'Designed core billing components',
    'exp.yandex2': 'Automated invoicing pipelines',
    'exp.yandex3': 'Database migration',
    'exp.yandex4': 'PostgreSQL optimization',
    'exp.yandex5': 'Production-grade CI/CD pipeline',
    'exp.post': 'Russian Post',
    'exp.postRole': 'National-Scale Workflow System',
    'exp.post1': 'Implemented Camunda-based automation',
    'exp.post2': 'Integrated international services',
    'exp.post3': 'Improved system transparency',
    'exp.crpt': 'CRPT',
    'exp.crptRole': 'Government-Integrated Tracking Platform',
    'exp.crpt1': 'Government authorization integration (Digital Signature)',
    'exp.crpt2': 'Working with cryptographic libraries',
    'exp.crpt3': 'Mission-critical backend support',
    'projects.title': 'AI Projects',
    'project.screenme': 'ScreenMe — AI Interview Platform',
    'project.screenmeDesc': 'My AI-powered product designed to automate candidate screening through interactive AI interviews. ScreenMe is not just a landing page, but a fully engineered system.',
    'project.screenme1': 'AI dialogue engine',
    'project.screenme2': 'Automated candidate reporting',
    'project.screenme3': 'Response evaluation logic',
    'project.screenme4': 'Scalable backend architecture',
    'project.screenme5': 'SaaS-ready infrastructure',
    'project.link': 'View Project',
    'project.analytics': 'AI Call Analytics System',
    'project.analyticsDesc': 'Production AI system processing up to 6,000 calls per month. Full quality control automation.',
    'project.analytics1': 'Transcription (Whisper)',
    'project.analytics2': 'Speaker diarization and role detection',
    'project.analytics3': 'NER and sentiment analysis',
    'project.analytics4': 'Detection of negative phrases',
    'project.analytics5': 'Automated manager performance reports',
    'project.analytics6': 'Parallel processing (~30 sec per 1 min audio)',
    'project.analytics7': 'Scalable to 8 concurrent jobs',
    'project.analytics8': 'PostgreSQL analytics storage',
    'contact.title': 'Let\'s Discuss Your Project?',
    'contact.description': 'If your system must scale reliably and handle complex financial or AI logic — let\'s build it properly.',
    'contact.email': 'Email',
    'contact.linkedin': 'LinkedIn',
    'contact.github': 'GitHub',
    'contact.telegram': 'Telegram',
    'footer.rights': '© 2026 Backend Architect. All rights reserved.',
  },
  ru: {
    'nav.about': 'Обо мне',
    'nav.projects': 'Проекты',
    'nav.contact': 'Контакты',
    'hero.name': 'Игорь Лапин',
    'hero.subtitle': 'Backend Архитектор',
    'hero.title': 'Архитектор масштабируемых backend-систем',
    'hero.description': 'Проектирую и внедряю backend-архитектуру для продуктов, где критичны',
    'hero.reliability': 'надежность',
    'hero.description2': 'производительность и финансовая логика.',
    'hero.industries': 'FinTech • Billing • High-Load • AI Platforms',
    'about.title': 'Обо мне',
    'about.description': 'Backend-инженер с',
    'about.years': '7+ годами',
    'about.description2': 'коммерческого опыта и',
    'about.leadYears': '2 годами',
    'about.description3': 'в роли Lead Engineer. Работал с крупными enterprise-системами, финансовыми модулями и государственными интеграциями.',
    'about.projects': 'Подключаюсь к проектам, где нужно:',
    'about.cap1': 'построить архитектуру с нуля',
    'about.cap2': 'внедрить биллинг или сложную транзакционную логику',
    'about.cap3': 'подготовить систему к росту нагрузки',
    'about.cap4': 'оптимизировать БД и устранить OOM / bottleneck',
    'about.cap5': 'интегрировать AI-модули',
    'about.work': 'Работаю как самостоятельный инженер или как',
    'about.fractional': 'fractional tech lead',
    'capabilities.mainTitle': 'Что я делаю',
    'edu.title': 'Образование',
    'edu.master': 'Магистратура',
    'edu.masterField': 'Мехатроника, робототехника и автоматизация',
    'edu.masterSchool': 'Карагандинский Государственный Технический Университет · 2017-2019',
    'edu.bachelor': 'Бакалавриат',
    'edu.bachelorField': 'Мхатроника, робототехника и автоматизация',
    'edu.bachelorSchool': 'Карагандинский Государственный Технический Университет',
    'lang.title': 'Языки',
    'lang.russian': 'Русский',
    'lang.english': 'Английский',
    'lang.native': 'Родной',
    'lang.professional': 'Профессиональный',
    'results.title': 'Ключевые результаты',
    'results.1': 'Ускорил генерацию отчетности в 10 раз (с 2 дней до 15 минут)',
    'results.2': 'Снизил пиковую нагрузку БД (OOM) со 100% до 40%',
    'results.3': 'Сократил количество workflow-ошибок на 50%',
    'results.4': 'Уменьшил MTTR инцидентов на 60%',
    'results.5': 'Реализовал систему обработки 6 000+ аудиозаписей в месяц',
    'skills.title': 'Форматы сотрудничества',
    'skills.audit': 'Архитектурный аудит',
    'skills.auditDesc': 'Анализ текущей архитектуры, выявление узких мест и рекомендации по улучшению',
    'skills.backend': 'Backend-разработка под ключ',
    'skills.backendDesc': 'Полный цикл разработки от проектирования до внедрения в production',
    'skills.performance': 'Performance-оптимизация',
    'skills.performanceDesc': 'Устранение bottleneck, оптимизация БД, снижение нагрузки и времени отклика',
    'skills.ai': 'AI-интеграция',
    'skills.aiDesc': 'Проектирование и внедрение AI-модулей в существующие системы',
    'skills.lead': 'Fractional Tech Lead',
    'skills.leadDesc': 'Техническое лидерство и архитектурные решения на проектной основе',
    'exp.title': 'Enterprise опыт',
    'exp.yandex': 'Yandex',
    'exp.yandexRole': 'Архитектура биллинга',
    'exp.yandex1': 'Проектирование и реализация биллингового ядра',
    'exp.yandex2': 'Автоматизация инвойсинга',
    'exp.yandex3': 'Миграция БД',
    'exp.yandex4': 'Оптимизация PostgreSQL',
    'exp.yandex5': 'Production CI/CD pipeline',
    'exp.post': 'Почта России',
    'exp.postRole': 'Национальная workflow-система',
    'exp.post1': 'Внедрение Camunda workflow',
    'exp.post2': 'Интеграции с международными сервисами',
    'exp.post3': 'Повышение прозрачности архитектуры',
    'exp.crpt': 'ЦРПТ',
    'exp.crptRole': 'Платформа с государственной интеграцией',
    'exp.crpt1': 'Интеграция с гос. авторизацией (ЭЦП)',
    'exp.crpt2': 'Работа с криптобиблиотеками',
    'exp.crpt3': 'Поддержка mission-critical системы',
    'projects.title': 'AI Проекты',
    'project.screenme': 'ScreenMe — AI Interview Platform',
    'project.screenmeDesc': 'Собственный AI-продукт для автоматизации первичного интервью кандидатов. ScreenMe — это не просто лендинг, а разработанная мной полноценная система.',
    'project.screenme1': 'AI-диалоговый движок',
    'project.screenme2': 'Генерация отчета по кандидату',
    'project.screenme3': 'Анализ ответов и поведенческих паттернов',
    'project.screenme4': 'Backend-архитектура под масштабирование',
    'project.screenme5': 'Подготовка к SaaS-модели',
    'project.link': 'Посмотреть проект',
    'project.analytics': 'AI Call Analytics System',
    'project.analyticsDesc': 'Production-система анализа звонков с обработкой до 6 000 аудио в месяц. Полная автоматизация контроля качества.',
    'project.analytics1': 'Транскрипция (Whisper)',
    'project.analytics2': 'Диаризация и определение ролей',
    'project.analytics3': 'NER и анализ тональности',
    'project.analytics4': 'Выявление плохих фраз',
    'project.analytics5': 'Автоматический отчет по менеджерам',
    'project.analytics6': 'Параллельная обработка (~30 сек на 1 мин аудио)',
    'project.analytics7': 'Масштабирование до 8 одновременных задач',
    'project.analytics8': 'Хранение аналитики в PostgreSQL',
    'contact.title': 'Обсудим проект?',
    'contact.description': 'Если вашему продукту нужна устойчивая архитектура, а не временное решение — напишите мне.',
    'contact.email': 'Email',
    'contact.linkedin': 'LinkedIn',
    'contact.github': 'GitHub',
    'contact.telegram': 'Telegram',
    'footer.rights': '© 2026 Backend Architect. Все права защищены.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}